apiVersion: v1
kind: Service
metadata:
  name: {{ template "cluster-proxy-addon.name" . }}-user
  labels:
    app: {{ template "cluster-proxy-addon.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "cluster-proxy-addon.name" . }}
    chart: {{ template "cluster-proxy-addon.chart" . }}
    component: cluster-proxy-addon-anp-server
    helm.sh/chart: {{ template "cluster-proxy-addon.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
     service.alpha.openshift.io/serving-cert-secret-name: cluster-proxy-user-proxy-serving-cert
spec:
  type: NodePort
  ports:
  - name: user-port
    port: 9092
    nodePort: {{ template "cluster-proxy-addon.userServiceNodePort" . }}
  selector:
    app: {{ template "cluster-proxy-addon.name" . }}
    component: cluster-proxy-addon-anp-server
    release: {{ .Release.Name }}
