apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cluster-proxy-addon.fullname" . }}
  labels:
    app: {{ template "cluster-proxy-addon.name" . }}
    chart: {{ template "cluster-proxy-addon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "cluster-proxy-addon.name" . }}
    helm.sh/chart: {{ template "cluster-proxy-addon.chart" . }}
    component: cluster-proxy-addon-serviceaccount
